name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: PHPUnit tests
          uses: MilesChou/php-tools-action/phpunit@master
          with:
              args: --configuration phpunit.xml.dist
        - name: PHPStan tests
          uses: MilesChou/php-tools-action/phpstan@master
          with:
              args: phpstan.neon.dist
        - name: psalm
          uses: psalm/psalm-github-actions@1.0.0
          with:
              configuration: psalm.xml
